apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: arungupta/greeting
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 5005
          name: "debug"
